// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpyiqxbdktckgoreexxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNweWlxeGJka3Rja2dvcmVleHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjgwNDEsImV4cCI6MjA2MDEwNDA0MX0.vwaHtdVvq3HhY0Dwabzw8CzjyC-KVa1H0Eqav1Ws75M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);